# Generated by Django 3.2.5 on 2021-07-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
