# Generated by Django 3.2.5 on 2021-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_rename_entrega_agendaentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='calendario/%Y%m')),
            ],
        ),
    ]
