# Generated by Django 3.2.5 on 2021-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='calendario/%Y%m'),
        ),
    ]
