# Generated by Django 3.2.5 on 2021-07-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_calendario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
